SELECT A.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') AS A
    JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') AS B
    ON A.CART_ID = B.CART_ID
ORDER BY CART_ID;