SELECT R.FOOD_TYPE AS FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX FROM REST_INFO GROUP BY FOOD_TYPE) AS SUB
ON R.FOOD_TYPE = SUB.FOOD_TYPE
WHERE FAVORITES = SUB.MAX
ORDER BY FOOD_TYPE DESC;