-- 코드를 입력하세요
WITH R1 AS
(
    SELECT MEMBER_ID, COUNT(*) AS MC
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT MEMBER_NAME AS MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
    INNER JOIN REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    INNER JOIN R1
    ON RR.MEMBER_ID = R1.MEMBER_ID
WHERE R1.MC = (SELECT MAX(MC) FROM R1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;